services:
  - type: web
    name: campus-workflow-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false  # You'll need to set this in Render dashboard
